<a href="https://colab.research.google.com/github/Mirsha-RG/tallerprograma2/blob/projects/ejercicio_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import pandas as pd
import numpy as np
from scipy.stats import norm

In [102]:
df = pd.read_csv('https://raw.githubusercontent.com/it-ces/Datasets/main/TMR.csv', decimal= ',')
df

        Año Fecha (dd/mm/aaaa)      TRM  Día del mes        Mes  Id Mes
0      2024         2024-01-01  3822.05            1      Enero       1
1      2023         2023-12-31  3822.05           31  Diciembre      12
2      2023         2023-12-30  3822.05           30  Diciembre      12
3      2023         2023-12-29  3822.05           29  Diciembre      12
4      2023         2023-12-28  3844.81           28  Diciembre      12
...     ...                ...      ...          ...        ...     ...
11719  1991         1991-12-01   643.42            1  Diciembre      12
11720  1991         1991-11-30   694.70           30  Noviembre      11
11721  1991         1991-11-29   694.70           29  Noviembre      11
11722  1991         1991-11-28   693.99           28  Noviembre      11
11723  1991         1991-11-27   693.32           27  Noviembre      11

[11724 rows x 6 columns]

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11724 entries, 0 to 11723
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Año                 11724 non-null  int64
 1   Fecha (dd/mm/aaaa)  11724 non-null  object
 2   TRM                 11724 non-null  float64
 3   Día del mes         11724 non-null  int64
 4   Mes                 11724 non-null  object
 5   Id Mes              11724 non-null  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 549.7+ KB

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11724 entries, 0 to 11723
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Año                 11724 non-null  int64
 1   Fecha (dd/mm/aaaa)  11724 non-null  object
 2   TRM                 11724 non-null  float64
 3   Día del mes         11724 non-null  int64
 4   Mes                 11724 non-null  object
 5   Id Mes              11724 non-null  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 549.7+ KB

In [105]:
anio_2023 = df[(df['Año'] == 2023)]
anio_2023

      Año Fecha (dd/mm/aaaa)      TRM  Día del mes        Mes  Id Mes
1    2023         2023-12-31  3822.05           31  Diciembre      12
2    2023         2023-12-30  3822.05           30  Diciembre      12
3    2023         2023-12-29  3822.05           29  Diciembre      12
4    2023         2023-12-28  3844.81           28  Diciembre      12
5    2023         2023-12-27  3871.45           27  Diciembre      12
..    ...                ...      ...          ...        ...     ...
361  2023         2023-01-05  4924.00            5      Enero       1
362  2023         2023-01-04  4842.26            4      Enero       1
363  2023         2023-01-03  4810.20            3      Enero       1
364  2023         2023-01-02  4810.20            2      Enero       1
365  2023         2023-01-01  4810.20            1      Enero       1

[365 rows x 6 columns]

In [106]:
media_2023 = anio_2023['TRM'].mean()
media_2023

np.float64(4325.050136986301)

In [107]:
std_2023 = df['TRM'].std()
std_2023

967.9331914881403

In [108]:
n_2023 = len(anio_2023)
Z = 1.96

error_std_2023 = std_2023 / np.sqrt(n_2023)

limite_inferior = media_2023 - (error_std_2023 * Z)
limite_superior = media_2023 + (error_std_2023 * Z)

print(limite_inferior, limite_superior)

4225.74881695908 4424.351457013523

In [109]:
febrero23 = anio_2023[(df['Mes'] =='Febrero')]
febrero23

/tmp/ipython-input-109-1108353459.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  febrero23 = anio_2023[(df['Mes'] =='Febrero')]

      Año Fecha (dd/mm/aaaa)      TRM  Día del mes      Mes  Id Mes
307  2023         2023-02-28  4808.14           28  Febrero       2
308  2023         2023-02-27  4849.65           27  Febrero       2
309  2023         2023-02-26  4849.65           26  Febrero       2
310  2023         2023-02-25  4849.65           25  Febrero       2
311  2023         2023-02-24  4853.90           24  Febrero       2
312  2023         2023-02-23  4924.91           23  Febrero       2
313  2023         2023-02-22  4950.33           22  Febrero       2
314  2023         2023-02-21  4918.94           21  Febrero       2
315  2023         2023-02-20  4918.94           20  Febrero       2
316  2023         2023-02-19  4918.94           19  Febrero       2
317  2023         2023-02-18  4918.94           18  Febrero       2
318  2023         2023-02-17  4966.33           17  Febrero       2
319  2023         2023-02-16  4878.24           16  Febrero       2
320  2023         2023-02-15  4783.24           15  Febrero       2
321  2023         2023-02-14  4818.62           14  Febrero       2
322  2023         2023-02-13  4777.73           13  Febrero       2
323  2023         2023-02-12  4777.73           12  Febrero       2
324  2023         2023-02-11  4777.73           11  Febrero       2
325  2023         2023-02-10  4742.05           10  Febrero       2
326  2023         2023-02-09  4769.85            9  Febrero       2
327  2023         2023-02-08  4775.99            8  Febrero       2
328  2023         2023-02-07  4776.25            7  Febrero       2
329  2023         2023-02-06  4669.74            6  Febrero       2
330  2023         2023-02-05  4669.74            5  Febrero       2
331  2023         2023-02-04  4669.74            4  Febrero       2
332  2023         2023-02-03  4584.44            3  Febrero       2
333  2023         2023-02-02  4639.04            2  Febrero       2
334  2023         2023-02-01  4648.70            1  Febrero       2

In [110]:
def nivel_deconfianza(datos, Z):

  media = datos.mean()
  std = datos.std()
  n = len(datos)
  error_std = std / np.sqrt(n)
  limite_inferior = media - (error_std * Z)
  limite_superior = media + (error_std * Z)

  return limite_inferior, limite_superior

In [111]:
print(nivel_deconfianza(anio_2023['TRM'], Z))
#FILTRADO2023

(np.float64(4292.255484628066), np.float64(4357.844789344536))

In [112]:
print(nivel_deconfianza(febrero23['TRM'], Z))
#FILTRADO2023

(np.float64(4764.568508393434), np.float64(4841.656491606566))